server {
    listen 80;
    server_name localhost;  # Или ваш IP-адрес

    root /usr/share/nginx/html;  # Путь к вашим статическим файлам
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;  # Для SPA
    }

    location /setting_house_admin {
        try_files $uri $uri/ /index.html;  # Перенаправляем на index.html для маршрутов
    }

    # Другие настройки, если нужны
}