server {

            listen 80;
            server_name 188.225.58.13;

            index index.html;

            location / {
                    root /var/www/188.225.58.13;
                    index index.html;
                    try_files $uri $uri/ /index.html;
            }
    }