server {
    listen 80;
    server_name 188.225.58.13;  # Или ваш IP-адрес

    root /usr/share/nginx/html;  # Путь к вашим статическим файлам
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;  # Для SPA
    }

    # Другие настройки, если нужны
}