name: Deploy to Server

on:
  push:
    branches:
      - main  # Установите нужную ветку для триггера

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run deployment commands
        run: |
          ssh -o StrictHostKeyChecking=no -vvv -T root@176.124.209.73 "cd school-monitor/ && git pull origin main && docker-compose down && docker-compose build && docker-compose up -d"
